#!/usr/bin/env bash
#
# prerequisites: install python
# sudo apt-get install python-numpy python-dev python-pip python-wheel
#
# configure with python
# PYTHON_BIN_PATH=/usr/bin/python ./configure
#
# press enter all the way
#
#bazel build --config=opt --config=rocm -c dbg --strip=never //tensorflow/tools/pip_package:build_pip_package --verbose_failures &&
if bazel build --config=opt --config=rocm //tensorflow/tools/pip_package:build_pip_package --verbose_failures
then
    if bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
    then
        pip uninstall -y tensorflow || true
        pip install /tmp/tensorflow_pkg/tensorflow-1.8.0-cp27-cp27mu-linux_x86_64.whl
    fi
fi
